language: node_js
node_js:
  - "0.10"

env:
  global:
    - secure: entbiF59zjgSiel6S8bsKUrZVCXKsun9OqO95ABoQ8EaLrnP536EGVN/LurT/9W1QXcxLVChTpYZRizrhIoEQPi4vOVLrA5yhWlTGQULXWGNMf0VDTKfXOSQ6pV45zPnlmK/UV4eWAtDa7KsfOlPvQeX1K1JqSijLhPANNykGAQ=
    - secure: YFYR9PLyfwpVVRoTeCz/0Cml2NDCrqUgufshdKxc5SM/l0Ix8XlP8eJ+s3CVArTzWJg9nzOopt9qaXtTbcN+Kr5SaMDpmjliXpmOGEkhx29dCTYuksjbGW44ImUWT2kaAARZnufPXrI7/QDxHjcaMWlR5wKveB/8m0FpEpd7YL4=

addons:
  sauce_connect: true    

services:
  - mongodb

before_install:
  - npm install -g grunt-cli

script: grunt test:travis

notifications:
  webhooks: http://cfa-project-monitor.herokuapp.com/projects/6ecc54d0-6abb-460b-97e4-ac4eae66d7a0/status